### PR TITLE
wait until viewController is dismissed before callback, fixes #47

### LINKED ISSUE #47: onSuccess called before camera activity closed
Having the camera view still running (while it is closing) AFTER the `onSuccess` callback is called means other plugins such as `cordova-plugin-dialog` won't work and have an internal violation.

This typically means I have to add a `setTimeout(..., 1000)` to my QR scanner to avoid the application from failing to re-open those plugins.

The simplest example of this would be (using `cordova-plugin-dialog`):

``` javascript
cloudSky.zBar.scan({}, function () {
  window.navigator.alert('This fails', function () {}, 'Text', 'OK')
}, functoin () {
  setTimeout(function () {
    window.navigator.alert('But this works... until you do the other one', function () {}, 'Text', 'OK')
  }, 1000)
})
```

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
ping @tjwoon this resolves #47 :+1: 
Simple fix, and as expected.

**Comment by dcousens** [comment]
ping @tjwoon

**Comment by dcousens** [comment]
ping @tjwoon :)

**Comment by MaicolBen** [comment]
This happens also in Android to me, so this PR won't solve completely

**Comment by dcousens** [comment]
@MaicolBen do you have a test case / reproduction code so I can verify this and fix it too?

**Pull request merged**
