### PR TITLE
Fix scanner never closing

### LINKED ISSUE #42: ZBar never closing
I have an issue when I try to rescan the same Qr Code, the scanner never exit but call the callback. It works good on Android but not IOS I have to click the cancel button to exit the view.

The iphone logs:
`Attempt to dismiss from view controller <MainViewController: 0x1576487a0> while a presentation or dismiss is in progress!`

### PR DESCRIPTION
**Pull request by MaicolBen**
Fixes #42

### CODE REVIEW

**Comment by dcousens** [comment]
@MaicolBen could you please rebase?

**Comment by MaicolBen** [comment]
Done

**Comment by dcousens** [comment]
LGTM,  @uniphonic if ACK please merge :)

**Comment by uniphonic** [comment]
Looks good to me. I've tested it out on an iOS device, and seems to run fine. I'm going to merge it. Thanks!

**Comment by uniphonic** [comment]
@MaicolBen Thanks for submitting the fix!

**Pull request merged**
